general {
    no_fade_in = true
    no_fade_out = true
}
background {
    monitor =
    path = $HOME/Pictures/Walls/wallhaven-l8xxep.jpg
    #    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3
    blur_size = 1
    noise = 0.01
}

label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/script/time_in_binary.py 0
    color = rgba(206, 218, 238, 0.8)
    font_size = 45
    font_family = Noto Sans
    position = 0, 10
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/script/time_in_binary.py 1
        color = rgba(206, 218, 238, 0.8)
    font_size = 45
    font_family = Noto Sans
    position = 0, -50
    halign = center
    valign = center
}


input-field {
    monitor =
    size = 200, 30
    outline_thickness = 1
    dots_center = true
    dots_size = 0.1
    dots_spacing = 0.3
    outer_color = rgba(206, 218, 238, 0.8)
    inner_color = rgba(206, 218, 238, 0)
    font_color = rgba(206, 218, 238, 0.8)
    color = rgba(206, 218, 238, 0.8)
    outer_color = rgba(206, 218, 238, 0.8)
    fade_on_empty = true
    hide_input = false
    position = 0, 20
    halign = center
    valign = bottom
}



label { # Clock
    monitor =
    text = $TIME
    shadow_passes = 1
    shadow_boost = 0.5
    color = $text_color
    font_size = 65
    font_family = $font_family_clock

    position = 0, 180
    halign = center
    valign = center
}
label { # Greeting
    monitor =
    text = Kou | Llunatic
    shadow_passes = 1
    shadow_boost = 0.5
    color = $text_color
    font_size = 20
    font_family = $font_family

    position = 0, 100
    halign = center
    valign = center
}

label { # Status
    monitor =
    text = cmd[update:5000] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprlock/status.sh
    shadow_passes = 1
    shadow_boost = 0.5
    color = $text_color
    font_size = 14
    font_family = Noto Sans

    position = 30, -30
    halign = left
    valign = top
}
